steps:
# Pull the existing image
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
    - '-c'
    - |
      docker pull gcr.io/sanchit909090/wcm:v1 || exit 0
# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/wcm', '--cache-from', 'gcr.io/$PROJECT_ID/wcm', '.' ]
# Push the docker image to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ["push", "gcr.io/$PROJECT_ID/wcm"]
# Deploy an image from Container Registry to Cloud Run
