steps:

# Build a docker image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/sanchit909090/wcm:latest', '.']
   id: 'build-image'
   waitFor: ['-']
   
# push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/sanchit909090/wcm:latest']
   id: 'push-image'
   waitFor: ['build-image']
    
# Train the model.
 - name: 'gcr.io/sanchit909090/wcm:latest'
   entrypoint: 'python'
   args: ['build/task.py',
          '--mode', 'train-model',
          '--project', 'sanchit909090',
          '--region', 'us-central1',
          '--job_name', 'custom_training',
          '--script_path', 'https://raw.githubusercontent.com/SANCHIT-GARG/WasteClassificationMgt/main/build/task.py',
          '--container_uri', 'gcr.io/sanchit909090/wcm:latest',
          '--model_serving_container_image_uri', 'us-docker.pkg.dev/vertex-ai/prediction/tf2-cpu.2-8:latest',
          '--model_display_name', 'wcm-model']
   id: 'Train Model'
   waitFor: ['push-image']

# Create an endpoint.
 - name: 'gcr.io/sanchit909090/wcm:latest'
   entrypoint: 'python'
   args: ['build/utils.py',
          '--mode', 'create-endpoint',
          '--project', 'sanchit909090',
          '--region', 'us-central1',
          '--endpoint_display_name', 'wcm-endpoint']
   id: 'Create Endpoint'
   waitFor: ['Train Model']
   
# Deploy the model.
 - name: 'gcr.io/sanchit909090/wcm:latest'
   entrypoint: 'python'
   args: ['build/utils.py',
          '--mode', 'deploy-model',
          '--project', 'sanchit909090',
          '--region', 'us-central1',
          '--endpoint_display_name', 'wcm-endpoint',
          '--model_display_name', 'wcm-model']
   id: 'Deploy Endpoint'
   waitFor: ['Create Endpoint']

images:
 - 'gcr.io/sanchit909090/wcm:latest'
